spring.datasource.url=jdbc:mysql://127.0.0.1:3307/academe_db?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=2005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#JWT signing key stored as Base64
jwt.secret=ZrnxEJO4DBaj7cm4tZQsttoUPoQqZzRIrxiN+ATVvp0=

#Token lifetime: 24 hours in milliseconds
jwt.expiration=86400000